### ISSUE TITLE
BehavioralTimeSeries failing when data contains NaNs

### ISSUE THREAD

**Issue by pauladkisson** [flatironinstitute/neurosift#219]
I have a time series on the Dandi Archive that contains a couple Nan values, which bricks the visualization (see below).

https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/6fa78218-f4d4-45f3-a627-5afe4aa88c3e/download/&dandisetId=001259&dandisetVersion=draft

If the link above doesn't work, go to https://dandiarchive.org/dandiset/001259/draft/files?location=sub-m53&page=1
and open sub-m53_ses-231029_behavior+ecephys+image.nwb in Neurosift, and visualize the processing/behavior/behavioral_time_series/encoder time series.

![Image](https://github.com/user-attachments/assets/237de571-b52d-4be8-9eb5-c28515fcfc36)

**Comment by bendichter** [comment]
@pauladkisson it looks like this dataset is embargoed so I am unable to reproduce.

**Comment by magland** [comment]
need to explore further in v2

**Comment by bendichter** [comment]
<img width="1709" alt="Image" src="https://github.com/user-attachments/assets/9c7e3d39-23a7-452d-bec9-e593305131c5" />

I now have access to this data and can reproduce this error

**Comment by bendichter** [comment]
@pauladkisson are the nan values in the timestamps or in the data field?

**Comment by pauladkisson** [comment]
> are the nan values in the timestamps or in the data field?

The data

**Comment by magland** [comment]
If you give me access to DANDI:001259 I can check it out.

**Comment by pauladkisson** [comment]
> If you give me access to DANDI:001259 I can check it out.

Done

**Comment by magland** [comment]
Hmmmm I still don't seem to have access. Should I be getting a confirmation email from dandi? My user name is magland.

**Comment by pauladkisson** [comment]
> Hmmmm I still don't seem to have access. Should I be getting a confirmation email from dandi? My user name is magland.

It already showed you as an owner on the dandiset. I will remove you and re-add and see if that helps.

**Comment by magland** [comment]
Okay I am able to access it now. I was using the wrong link.

I think the issue is that the "data" dataset inside the encoder TimeSeries has a weird type. I would have expected it to be an array of shape [1407445, 2]. Instead it looks like it is an array of shape [1407445] of non-numeric data type, where each element is an array of shape 2.

See

![Image](https://github.com/user-attachments/assets/1cdff1bd-44fe-411a-98f9-b28134267bc6)

Compare that to a valid SpatialSeries example
https://neurosift.app/nwb?url=https://api.dandiarchive.org/api/assets/7fa1413a-97af-4fcc-9e5d-dae4c93ab388/download/&dandisetId=000697&dandisetVersion=draft&tab=%2Fprocessing%2Fwt%3Anacre%3A+behavior+right+lane%2FPosition%2FChamber+position

that looks like this

![Image](https://github.com/user-attachments/assets/5f254580-1dad-4150-9bb7-e340eb7248bc)

**Comment by pauladkisson** [comment]
> I think the issue is that the "data" dataset inside the encoder TimeSeries has a weird type. I would have expected it to be an array of shape [1407445, 2]. Instead it looks like it is an array of shape [1407445] of non-numeric data type, where each element is an array of shape 2.

It's a 1D variable, so it should have shape (N,), but I am seeing a weird dtype for this session (complex numbers when I read it into a numpy array). I will check with the experimenter to see if there is any explanation.

**Comment by magland** [comment]
ah yes, I think complex numbers would explain this issue.

**Comment by bendichter** [comment]
Should look into how this data was created. Pynwb matnwb and the validator should flag complex values

**Comment by pauladkisson** [comment]
> Pynwb matnwb and the validator should flag complex values

I'm not seeing it in the list of checks: https://nwbinspector.readthedocs.io/en/dev/api/checks.html
Maybe something we should add?

**Comment by pauladkisson** [comment]
I updated the files on the dandiset to remove the imaginary part of this time series, so this is no longer an issue for this dandiset.
